rules:
  indent:
    - 2
    - 4
    - SwitchCase: 1
  linebreak-style:
    - 2
    - unix
  no-unused-vars:
    - 0
  prettier/prettier: error
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended,prettier'
plugins:
  - prettier